### ISSUE TITLE
LifeXPost save() accepts duplicates

### ISSUE THREAD

**Issue by coolharsh55** [coolharsh55/coolharsh55.github.io#84]
The LifeXPost accepts duplicate entries in the form of (week, idea) pairs, which then cause problems in the .get() queries.

**Comment by coolharsh55** [comment]
```python
Internal Server Error: /experiments/week14/app-project/ Traceback (most recent call last):

File "/opt/bitnami/python/lib/python2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
  response = wrapped_callback(request, *callback_args, **callback_kwargs)
File "/opt/bitnami/apps/django/django_projects/harshp.com/lifeX/views.py", line 280, in post
  post = LifeXPost.objects.get(week=week, idea=idea)
File "/opt/bitnami/python/lib/python2.7/site-packages/django/db/models/manager.py", line 127, in manager_method
  return getattr(self.get_queryset(), name)(*args, **kwargs)
File "/opt/bitnami/python/lib/python2.7/site-packages/django/db/models/query.py", line 338, in get
  (self.model._meta.object_name, num)
MultipleObjectsReturned: get() returned more than one LifeXPost — it returned 2!

Request repr(): <WSGIRequest path:/experiments/week14/app-project/, GET:<QueryDict: {}>, POST:<QueryDict: {}>, COOKIES:{}, META:{'CONTEXT_DOCUMENT_ROOT': ‘/opt/bitnami/apache2/htdocs’,

'CONTEXT_PREFIX': '',
u'CSRF_COOKIE': u'pNqN2eqNIEudWF297z0UFMOJILQALmQH',
'DOCUMENT_ROOT': '/opt/bitnami/apache2/htdocs',
'GATEWAY_INTERFACE': 'CGI/1.1',
'HTTP_ACCEPT': 'text/html,text/plain,text/xml,text/*,application/xml,application/xhtml+xml,application/rss+xml,application/atom+xml,application/rdf+xml,application/php,application/x-php,application/x-httpd-php',
'HTTP_ACCEPT_ENCODING': 'gzip',
'HTTP_ACCEPT_LANGUAGE': 'en',
'HTTP_CONNECTION': 'close',
'HTTP_HOST': 'lifex.harshp.com',
'HTTP_USER_AGENT': 'Mozilla/5.0 (compatible; MJ12bot/v1.4.5; http://www.majestic12.co.uk/bot.php?+)',
'LD_LIBRARY_PATH': '/opt/bitnami/sqlite/lib:/opt/bitnami/python/lib:/opt/bitnami/mysql/lib:/opt/bitnami/apache2/lib:/opt/bitnami/common/lib:/opt/bitnami/ruby/lib/ruby/gems/2.0.0/gems/passenger-4.0.57/lib:/opt/bitnami/memcached/lib:/opt/bitnami/varnish/lib:/opt/bitnami/varnish/lib/varnish:/opt/bitnami/varnish/lib/varnish/vmods:/opt/bitnami/redis/lib:/opt/bitnami/perl/lib:/opt/bitnami/perl/lib/5.16.3/x86_64-linux-thread-multi/CORE:/opt/bitnami/git/lib:/opt/bitnami/nginx/lib:/opt/bitnami/mongodb/lib:/opt/bitnami/sqlite/lib:/opt/bitnami/apps/django/lib/python2.7/site-packages:/opt/bitnami/mysql/lib:/opt/bitnami/postgresql/lib:/opt/bitnami/apache2/lib:/opt/bitnami/python/lib:/opt/bitnami/subversion/lib:/opt/bitnami/ruby/lib:/opt/bitnami/common/lib:',
'PATH_INFO': u'/experiments/week14/app-project/',
'PATH_TRANSLATED': '/opt/bitnami/apps/django/django_projects/harshp.com/harshp/wsgi.py/experiments/week14/app-project/',
'QUERY_STRING': '',
'REMOTE_ADDR': '199.192.207.146',
'REMOTE_PORT': '53858',
'REQUEST_METHOD': 'GET',
'REQUEST_SCHEME': 'http',
'REQUEST_URI': '/experiments/week14/app-project/',
'SCRIPT_FILENAME': '/opt/bitnami/apps/django/django_projects/harshp.com/harshp/wsgi.py',
'SCRIPT_NAME': u'',
'SERVER_ADDR': '172.31.39.159',
'SERVER_ADMIN': 'you@example.com',
'SERVER_NAME': 'lifex.harshp.com',
'SERVER_PORT': '80',
'SERVER_PROTOCOL': 'HTTP/1.0',
'SERVER_SIGNATURE': '',
'SERVER_SOFTWARE': 'Apache',
'mod_wsgi.application_group': '',
'mod_wsgi.callable_object': 'application',
'mod_wsgi.enable_sendfile': '0',
'mod_wsgi.handler_script': '',
'mod_wsgi.input_chunked': '0',
'mod_wsgi.listener_host': '',
'mod_wsgi.listener_port': '80',
'mod_wsgi.process_group': 'wsgi-djangostack',
'mod_wsgi.queue_start': '1441667246343364',
'mod_wsgi.request_handler': 'wsgi-script',
'mod_wsgi.script_reloading': '1',
'mod_wsgi.version': (3, 5),
'wsgi.errors': <mod_wsgi.Log object at 0x7f20216470b0>,
'wsgi.file_wrapper': <built-in method file_wrapper of mod_wsgi.Adapter object at 0x7f2021d74a80>,
'wsgi.input': <mod_wsgi.Input object at 0x7f202055d0b0>,
'wsgi.multiprocess': True,
'wsgi.multithread': True,
'wsgi.run_once': False,
'wsgi.url_scheme': 'http',
'wsgi.version': (1, 0)}>
```

**Comment by coolharsh55** [comment]
```
Internal Server Error: /experiments/week14/app-project/ Traceback (most recent call last):

File "/opt/bitnami/python/lib/python2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
  response = wrapped_callback(request, *callback_args, **callback_kwargs)
File "/opt/bitnami/apps/django/django_projects/harshp.com/lifeX/views.py", line 280, in post
  post = LifeXPost.objects.get(week=week, idea=idea)
File "/opt/bitnami/python/lib/python2.7/site-packages/django/db/models/manager.py", line 127, in manager_method
  return getattr(self.get_queryset(), name)(*args, **kwargs)
File "/opt/bitnami/python/lib/python2.7/site-packages/django/db/models/query.py", line 338, in get
  (self.model._meta.object_name, num)
MultipleObjectsReturned: get() returned more than one LifeXPost — it returned 2!

Request repr(): <WSGIRequest path:/experiments/week14/app-project/, GET:<QueryDict: {}>, POST:<QueryDict: {}>, COOKIES:{}, META:{'CONTEXT_DOCUMENT_ROOT': ‘/opt/bitnami/apache2/htdocs’,

'CONTEXT_PREFIX': '',
u'CSRF_COOKIE': u'pNqN2eqNIEudWF297z0UFMOJILQALmQH',
'DOCUMENT_ROOT': '/opt/bitnami/apache2/htdocs',
'GATEWAY_INTERFACE': 'CGI/1.1',
'HTTP_ACCEPT': 'text/html,text/plain,text/xml,text/*,application/xml,application/xhtml+xml,application/rss+xml,application/atom+xml,application/rdf+xml,application/php,application/x-php,application/x-httpd-php',
'HTTP_ACCEPT_ENCODING': 'gzip',
'HTTP_ACCEPT_LANGUAGE': 'en',
'HTTP_CONNECTION': 'close',
'HTTP_HOST': 'lifex.harshp.com',
'HTTP_USER_AGENT': 'Mozilla/5.0 (compatible; MJ12bot/v1.4.5; http://www.majestic12.co.uk/bot.php?+)',
'LD_LIBRARY_PATH': '/opt/bitnami/sqlite/lib:/opt/bitnami/python/lib:/opt/bitnami/mysql/lib:/opt/bitnami/apache2/lib:/opt/bitnami/common/lib:/opt/bitnami/ruby/lib/ruby/gems/2.0.0/gems/passenger-4.0.57/lib:/opt/bitnami/memcached/lib:/opt/bitnami/varnish/lib:/opt/bitnami/varnish/lib/varnish:/opt/bitnami/varnish/lib/varnish/vmods:/opt/bitnami/redis/lib:/opt/bitnami/perl/lib:/opt/bitnami/perl/lib/5.16.3/x86_64-linux-thread-multi/CORE:/opt/bitnami/git/lib:/opt/bitnami/nginx/lib:/opt/bitnami/mongodb/lib:/opt/bitnami/sqlite/lib:/opt/bitnami/apps/django/lib/python2.7/site-packages:/opt/bitnami/mysql/lib:/opt/bitnami/postgresql/lib:/opt/bitnami/apache2/lib:/opt/bitnami/python/lib:/opt/bitnami/subversion/lib:/opt/bitnami/ruby/lib:/opt/bitnami/common/lib:',
'PATH_INFO': u'/experiments/week14/app-project/',
'PATH_TRANSLATED': '/opt/bitnami/apps/django/django_projects/harshp.com/harshp/wsgi.py/experiments/week14/app-project/',
'QUERY_STRING': '',
'REMOTE_ADDR': '199.192.207.146',
'REMOTE_PORT': '53858',
'REQUEST_METHOD': 'GET',
'REQUEST_SCHEME': 'http',
'REQUEST_URI': '/experiments/week14/app-project/',
'SCRIPT_FILENAME': '/opt/bitnami/apps/django/django_projects/harshp.com/harshp/wsgi.py',
'SCRIPT_NAME': u'',
'SERVER_ADDR': '172.31.39.159',
'SERVER_ADMIN': 'you@example.com',
'SERVER_NAME': 'lifex.harshp.com',
'SERVER_PORT': '80',
'SERVER_PROTOCOL': 'HTTP/1.0',
'SERVER_SIGNATURE': '',
'SERVER_SOFTWARE': 'Apache',
'mod_wsgi.application_group': '',
'mod_wsgi.callable_object': 'application',
'mod_wsgi.enable_sendfile': '0',
'mod_wsgi.handler_script': '',
'mod_wsgi.input_chunked': '0',
'mod_wsgi.listener_host': '',
'mod_wsgi.listener_port': '80',
'mod_wsgi.process_group': 'wsgi-djangostack',
'mod_wsgi.queue_start': '1441667246343364',
'mod_wsgi.request_handler': 'wsgi-script',
'mod_wsgi.script_reloading': '1',
'mod_wsgi.version': (3, 5),
'wsgi.errors': <mod_wsgi.Log object at 0x7f20216470b0>,
'wsgi.file_wrapper': <built-in method file_wrapper of mod_wsgi.Adapter object at 0x7f2021d74a80>,
'wsgi.input': <mod_wsgi.Input object at 0x7f202055d0b0>,
'wsgi.multiprocess': True,
'wsgi.multithread': True,
'wsgi.run_once': False,
'wsgi.url_scheme': 'http',
'wsgi.version': (1, 0)}>
`
```

**Comment by coolharsh55** [comment]
```
Internal Server Error: /experiments/week43/journaling/ Traceback (most recent call last):

File "/opt/bitnami/python/lib/python2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
  response = wrapped_callback(request, *callback_args, **callback_kwargs)
File "/opt/bitnami/apps/django/django_projects/harshp.com/lifeX/views.py", line 280, in post
  post = LifeXPost.objects.get(week=week, idea=idea)
File "/opt/bitnami/python/lib/python2.7/site-packages/django/db/models/manager.py", line 127, in manager_method
  return getattr(self.get_queryset(), name)(*args, **kwargs)
File "/opt/bitnami/python/lib/python2.7/site-packages/django/db/models/query.py", line 338, in get
  (self.model._meta.object_name, num)
MultipleObjectsReturned: get() returned more than one LifeXPost — it returned 2!

Request repr(): <WSGIRequest path:/experiments/week43/journaling/, GET:<QueryDict: {}>, POST:<QueryDict: {}>, COOKIES:{}, META:{'CONTEXT_DOCUMENT_ROOT': ‘/opt/bitnami/apache2/htdocs’,

'CONTEXT_PREFIX': '',
u'CSRF_COOKIE': u'J8bWnIB8mC2tnuN7zQSwAI5GYAvH9q5b',
'DOCUMENT_ROOT': '/opt/bitnami/apache2/htdocs',
'GATEWAY_INTERFACE': 'CGI/1.1',
'HTTP_ACCEPT': 'text/html,text/plain,text/xml,text/*,application/xml,application/xhtml+xml,application/rss+xml,application/atom+xml,application/rdf+xml,application/php,application/x-php,application/x-httpd-php',
'HTTP_ACCEPT_ENCODING': 'gzip',
'HTTP_ACCEPT_LANGUAGE': 'en',
'HTTP_CONNECTION': 'close',
'HTTP_HOST': 'lifex.harshp.com',
'HTTP_USER_AGENT': 'Mozilla/5.0 (compatible; MJ12bot/v1.4.5; http://www.majestic12.co.uk/bot.php?+)',
'LD_LIBRARY_PATH': '/opt/bitnami/sqlite/lib:/opt/bitnami/python/lib:/opt/bitnami/mysql/lib:/opt/bitnami/apache2/lib:/opt/bitnami/common/lib:/opt/bitnami/ruby/lib/ruby/gems/2.0.0/gems/passenger-4.0.57/lib:/opt/bitnami/memcached/lib:/opt/bitnami/varnish/lib:/opt/bitnami/varnish/lib/varnish:/opt/bitnami/varnish/lib/varnish/vmods:/opt/bitnami/redis/lib:/opt/bitnami/perl/lib:/opt/bitnami/perl/lib/5.16.3/x86_64-linux-thread-multi/CORE:/opt/bitnami/git/lib:/opt/bitnami/nginx/lib:/opt/bitnami/mongodb/lib:/opt/bitnami/sqlite/lib:/opt/bitnami/apps/django/lib/python2.7/site-packages:/opt/bitnami/mysql/lib:/opt/bitnami/postgresql/lib:/opt/bitnami/apache2/lib:/opt/bitnami/python/lib:/opt/bitnami/subversion/lib:/opt/bitnami/ruby/lib:/opt/bitnami/common/lib:',
'PATH_INFO': u'/experiments/week43/journaling/',
'PATH_TRANSLATED': '/opt/bitnami/apps/django/django_projects/harshp.com/harshp/wsgi.py/experiments/week43/journaling/',
'QUERY_STRING': '',
'REMOTE_ADDR': '199.192.207.146',
'REMOTE_PORT': '58256',
'REQUEST_METHOD': 'GET',
'REQUEST_SCHEME': 'http',
'REQUEST_URI': '/experiments/week43/journaling/',
'SCRIPT_FILENAME': '/opt/bitnami/apps/django/django_projects/harshp.com/harshp/wsgi.py',
'SCRIPT_NAME': u'',
'SERVER_ADDR': '172.31.39.159',
'SERVER_ADMIN': 'you@example.com',
'SERVER_NAME': 'lifex.harshp.com',
'SERVER_PORT': '80',
'SERVER_PROTOCOL': 'HTTP/1.0',
'SERVER_SIGNATURE': '',
'SERVER_SOFTWARE': 'Apache',
'mod_wsgi.application_group': '',
'mod_wsgi.callable_object': 'application',
'mod_wsgi.enable_sendfile': '0',
'mod_wsgi.handler_script': '',
'mod_wsgi.input_chunked': '0',
'mod_wsgi.listener_host': '',
'mod_wsgi.listener_port': '80',
'mod_wsgi.process_group': 'wsgi-djangostack',
'mod_wsgi.queue_start': '1441667343025742',
'mod_wsgi.request_handler': 'wsgi-script',
'mod_wsgi.script_reloading': '1',
'mod_wsgi.version': (3, 5),
'wsgi.errors': <mod_wsgi.Log object at 0x7f2019cef870>,
'wsgi.file_wrapper': <built-in method file_wrapper of mod_wsgi.Adapter object at 0x7f2014111d50>,
'wsgi.input': <mod_wsgi.Input object at 0x7f2019c64970>,
'wsgi.multiprocess': True,
'wsgi.multithread': True,
'wsgi.run_once': False,
'wsgi.url_scheme': 'http',
'wsgi.version': (1, 0)}>
```
